apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-server-deployment
spec:
  replicas: 3

  selector:
    matchLabels:
      app: my-server

  template:
    metadata:
      labels:
        app: my-server

    spec:
      containers:
        - name: my-server
          image: sonah5009/my-server:v1

          ports:
            - containerPort: 3000

          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 3

          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 3

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
