services:
  app:
    build:
      context: ../1. Linux + HTTP + Node.js
      dockerfile: ../3. Docker/Dockerfile
    # ports:
    #   - "3000:3000"

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app
